language: android
jdk:
- oraclejdk8
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
env:
  global:
  - ADB_INSTALL_TIMEOUT=20
  matrix:
  - ANDROID_TARGET=android-25 ANDROID_ABI=x86
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-25
  - android-25
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_dc96894d3972_key -iv $encrypted_dc96894d3972_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
script:
- "./gradlew clean"
- "./gradlew check"
- "./gradlew jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: DH476lKsOoCjJ5m2+d5TykjXwA6fSQdON8k8mGI0kSoSzVZx1HD3lefWl48TfCb6RmMUglKrLGXYXzHpldoWsbFLHcMqq/PoMTy6GrZFoDcYWgkiILVZlVzfFkzEXh/odo2deTngCc4WZhnSuWgrmiP4bkgKocCc12ilHLQUmC/YCxx72XKgBK9BKpyJfse7vWcrOZV4OdarjC2PIDA0anikeoSmid78VIdxfLJr+RScZKGbdKhyOjiROboBEkwr+R6URUQOP5uzBjI0LmYr6dsG8IDwtYqvLYA9CxH2WXYeNunFWHZjFQuX+txbUOn1FXh+2ti8l019StcQWqd1fQwb4bTPJLky9aEbyo1CizQFpQBHfbm4IadPhvvD5VcFFj9qFms/T5wxY9oNBO39iclfKYnol0audWI7chxT/M2ZOI0x9G7tVHCHv2nU6uwLk5CE4sB9mWfDC00d/7xIzHhqNVFson9nSsfoGz1oWc0JMaz6qQHB6WJCAuKOucCmJEXf2yahPzpMCjnjeSsKqkevKVyh42QsjhfHWC+fuPyjAjH8WLkKjeQpqmSjqUH/+lV5MrSC2R8IZ9ITaWiStQ8d/x/GuYIeBKiNbbVXBhSwaudjvutTYXGuQ0Dmv5mIfHvgGrZDtiynWk7sE7swB/g6B74W/MtdOZLSAdOm6Uo=
